platform :ios, '12.0'

use_frameworks!
inhibit_all_warnings!
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
        end
    end
end
def shared_pods
  pod 'FolioReaderKit', path: '../'
end

def testing_pods
  pod 'Quick', '1.3.2'
  pod 'Nimble', '7.3.1' 
end

target 'Example' do
  shared_pods
end

target 'Storyboard-Example' do
	shared_pods
end

target 'MultipleInstance-Example' do
    shared_pods
end

target 'FolioReaderTests' do
  shared_pods
  testing_pods
end
